[package]
name = "banking"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "banking"

[[bin]]
path = "src/main.rs"
name = "banking-cli"

[dependencies]
csv = "1.1.6"
serde = { version = "1", features = ["derive"] }
